pipeline {
    agent {
        docker {
            image 'maven:3.8-openjdk-11'
            args '-v $HOME/.m2:/root/.m2 -v $(pwd):/app -w /app'
        }
    }
    
    stages {
        stage('mvn test') {
            steps {
                sh 'mvn clean test'
            }
        }
    }
    
    post {
        always {
            jacoco( 
                execPattern: 'target/*.exec',
                classPattern: 'target/classes',
                sourcePattern: 'src/main/java',
                exclusionPattern: 'src/test*'
            )
        }
    }
}