pipeline {
    agent {
        docker {
            image 'maven:3.8-openjdk-11'
            args '-v $HOME/.m2:/root/.m2 -v /var/lib/jenkins/workspace/petclinic-ci-job:/app -w /app'
        }
    }
    
    stages {
        stage('mvn test') {
            steps {
                sh 'mvn clean test'
            }
        }
    }
}
